# Site settings
title: Eat. Drink. Code. Wander.
email: sean.dwyer@gmail.com
description: >
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://braindump.io" # the base hostname & protocol for your site
twitter_username: reywood
github_username:  reywood

# Build settings
markdown: kramdown
highlighter: pygments
exclude:
    - Gemfile
    - vendor
