# Site settings
title: braindump.io
email: sean.dwyer@gmail.com
description: Eat. Drink. Code. Wander.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://braindump.io" # the base hostname & protocol for your site
twitter_username: reywood
github_username:  reywood

# Build settings
markdown: kramdown
highlighter: pygments
exclude:
    - Gemfile
    - vendor
    - about.md
